# fly.toml app configuration file generated for treasure-hunt-api on 2024-06-10T21:23:16+04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'treasure-hunt-api'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[env]
PGHOST = "ep-icy-breeze-a26muogc.eu-central-1.aws.neon.tech"
PGDATABASE = "treasure-hunt"
PGUSER = "treasure-hunt_owner"
PGPASSWORD = "vxrVADSl3g9O"
ENDPOINT_ID = "ep-icy-breeze-a26muogc"

[[vm]]
  size = 'shared-cpu-1x'
